site_name: Kraud Cloud
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      anchor_linenums: true

  - pymdownx.superfences
