site_name: Kraud Cloud Documentation
theme:
  logo: assets/logo.svg
  name: material
  custom_dir: overrides
  features:
    - content.tabs.link
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.instant

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list:
  - md_in_html:
  - admonition:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Home:
      - Introduction: index.md
      - Mission: mission.md
  - Getting started:
    - Setup: quickstart/setup.md
    - Container Images: quickstart/images.md
    - Incoming Connections: quickstart/ingress.md
    - Persistent Volumes: quickstart/volumes.md
    - Confidential Compute: quickstart/confidential.md
  - Specification:
    - Products: specification/products.md
  - Technology:
    - Compute:  technology/architecture.md
    - Network:  technology/vpc.md
    - Storage:  technology/storage.md
    - Confidential Containers: technology/confidential.md
