site_name: Kraud Cloud Documentation
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.instant

plugins:
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list:
  - md_in_html:
  - admonition:



# Page tree
nav:
  - Home:
      - Introduction: index.md
      - Mission: mission.md
  - Getting started:
    - Setup: quickstart/setup.md
    - Container Images: quickstart/images.md
    - Incomming Connections: quickstart/ingress.md
    - Persistent Volumes: quickstart/volumes.md
    - Confidential Compute: quickstart/confidential.md
